---
name: test (go)
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Download
        run: go mod download all

      - name: Build
        run: go build -v -o out/ ./...

      - name: Unit Test
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 2
          retry_on: error
          command: |
            go test -v -shuffle=on -coverpkg "$(go list || go list -m | head -1)/..." -coverprofile cover.out ./...

      # - name: Fail when coverage below threshold
      #   uses: vladopajic/go-test-coverage@v2
      #   with:
      #     profile: cover.out
      #     local-prefix: github.com/PDOK/betterstack-exporter
      #     threshold-total: 80  # 80% overall coverage is the minimum

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: cover.out
          report: true
          chart: false
          amend: false
          reuse-go: true
        if: |
          github.event_name == 'push'
        continue-on-error: false
